project:
  type: website

website:
  title: "Masaki Eguchi"
  navbar:
    
    pinned: true
    
    left:
      - href: "cv/index.qmd"
        text: "CV"
      - href: "research/index.qmd"
        text: "Research"
      - href: "blog/index.qmd"
        text: "Blog"
      - href: "tools/index.qmd"
        text: "Tools"

format:
  html:
    theme: 
      - Litera
      - styles.scss
    toc: true
    code-link: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

editor: visual

