project:
  type: website
  output-dir: ../docs
  # pre-render: Rscript _scripts/populate_bib_yaml.R
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "!drafts/"
    - "!publications/journal_articles/example-publication/" #this is template yaml file

# Freeze settings for computational content
execute:
  freeze: auto

bibliography: /Users/eguchi/Zotero/exports/references.bib
csl: _styles/apa.csl

pagetitle: "{{< meta title >}} | Masaki EGUCHI"
author-meta: "Masaki EGUCHI, Ph.D."


website:
  title: "Masaki EGUCHI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: research/index.qmd
      #   text: Research
      - href: publications/index.qmd
        text: Publications
      - text: Teaching
        menu:
          - href: teaching/index.qmd
            text: All Courses
          - href: teaching/classes/Tohoku-2025/index.qmd
            text: Linguistic Data Analysis I
          - href: teaching/classes/Tohoku-2026/index.qmd
            text: Linguistic Data Analysis II  
      # - href: tutorials/index.qmd
      #   text: Tutorials
      - href: tools/index.qmd
        text: Tools
      - href: blog/index.qmd
        text: Blog
      # - about.qmd

    right:
      - icon: github
        href: https://github.com/egumasa
        aria-label: GitHub
        rel: me
      - icon: linkedin
        href: https://www.linkedin.com/in/masaki-eguchi-861302162
        aria-label: LinkedIn
        rel: me
      - text: <i class="ai ai-orcid"></i>
        href: https://orcid.org/0000-0002-0791-4935
        aria-label: ORCID
        target: _blank
      - text: <i class="ai ai-google-scholar"></i>
        href: https://scholar.google.com/citations?user=adPF2RgAAAAJ&hl=en
        aria-label: Google Scholar
        target: _blank
  page-footer:
    background: light # or `dark` or omit this option altogether (footer color will match page body color)
    left: Copyright 2026, Masaki Eguchi
    right: This website is built with <i class="bi bi-heart-fill"></i>, [<i class="bi bi-github"></i>](https://github.com/egumasa/egumasa.github.io){target=_blank}, [R](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      - cosmo
      - _styles/styles.scss
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

editor: source

